version: "3.9"

services:
  nextjs:
    image: ghcr.io/naveenraj-g/bezs:latest
    container_name: bezs
    env_file:
      - .env
    networks:
      - bezs-net
    volumes:
      - /root/bezs/logs:/app/logs
      - /root/bezs/uploads:/app/uploads
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  bezs-net:
    external: true
